name: JustTAB
version: ${project.version}
main: com.example.justtab.JustTAB
api-version: '1.21'
authors: [YourName]
softdepend: [LuckPerms]
permissions:
  justtab.reload:
    description: Reload the configuration
    default: op